# Generated by Django 2.2 on 2020-04-13 15:02

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200301_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Category_documents', validators=[utils.validators.validate_file_size, utils.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='categorylist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Category_photos', validators=[utils.validators.validate_file_size, utils.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.CategoryList'),
        ),
    ]
