# Generated by Django 2.2 on 2020-04-13 13:47

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200301_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='taskList_photos', validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='due_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
