# Generated by Django 2.2 on 2020-04-13 13:58

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200413_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='taskList_documents', validators=[utils.validators.validate_file_size, utils.validators.validate_extension]),
        ),
    ]
